TRGDIR=.
OBJ=./obj
SRC=./src
INC=./inc
FLAGS= -Wall -g

${TRGDIR}/main: ${OBJ} ${OBJ}/main.o ${OBJ}/package.o\
                     ${OBJ}/node.o ${OBJ}/dequeue.o ${OBJ}/sort.o
	g++ -o ${TRGDIR}/main ${OBJ}/main.o ${OBJ}/package.o\
                     ${OBJ}/node.o ${OBJ}/dequeue.o ${OBJ}/sort.o 
                   
${OBJ}:
	mkdir ${OBJ}

${OBJ}/main.o: ${SRC}/main.cpp inc/graph.h 
	g++ -c ${FLAGS} -o ${OBJ}/main.o ${SRC}/main.cpp

${OBJ}/gamestate.o: ${SRC}/gamestate.cpp inc/gamestate.h
	g++ -c ${FLAGS} -o ${OBJ}/gamestate.o ${SRC}/gamestate.cpp

${OBJ}/vertex.o: ${SRC}/vertex.cpp inc/vertex.h
	g++ -c ${FLAGS} -o ${OBJ}/vertex.o ${SRC}/vertex.cpp

${OBJ}/edge.o: ${SRC}/edge.cpp inc/edge.h
	g++ -c ${FLAGS} -o ${OBJ}/edge.o ${SRC}/edge.cpp

${OBJ}/node.o: ${SRC}/node.cpp inc/node.h
	g++ -c ${FLAGS} -o ${OBJ}/node.o ${SRC}/node.cpp

${OBJ}/graph.o: ${SRC}/graph.cpp inc/graph.h
	g++ -c ${FLAGS} -o ${OBJ}/graph.o ${SRC}/graph.cpp

${OBJ}/dequeue.o: ${SRC}/dequeue.cpp inc/dequeue.h
	g++ -c ${FLAGS} -o ${OBJ}/dequeue.o ${SRC}/dequeue.cpp

run:
	${TRGDIR}/main

clean:
	rm -f ${TRGDIR}/main ${OBJ}/*